package com.cairone.sdlpocjpa.entities;
// Generated 08/06/2016 10:42:19 by Hibernate Tools 3.4.0.CR1


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Localidad generated by hbm2java
 */
@Entity @Table(name="LOCALIDAD")
public class LocalidadEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	@EmbeddedId private LocalidadPKEntity pk = null;
    
	@OneToOne @JoinColumn(name = "loc_pais", insertable = false, updatable = false)
	private PaisEntity pais = null;
	
	@OneToOne @JoinColumns({
		@JoinColumn(name = "loc_pais", referencedColumnName = "pais", insertable = false, updatable = false),
		@JoinColumn(name = "loc_provincia", referencedColumnName = "provincia", insertable = false, updatable = false)
	})
	private ProvinciaEntity provincia = null;
	
	@Column(name="loc_postal", nullable=false, length=12, insertable = false, updatable = false) 
	private String locPostal = null;
	
	@Column(name="descripcion", length=40)
	private String descripcion = null;
	
	@Column(name="prefijo")
	private Integer prefijo = null;
     
	public LocalidadEntity() {
		this.pk = new LocalidadPKEntity();
	}

	public PaisEntity getPais() {
		return pais;
	}

	public void setPais(PaisEntity pais) {
		this.pais = pais;
		this.pk.setLocPais(pais.getId());
	}

	public ProvinciaEntity getProvincia() {
		return provincia;
	}

	public void setProvincia(ProvinciaEntity provincia) {
		this.provincia = provincia;
		this.pk.setLocProvincia(provincia.getId());
	}

	public String getLocPostal() {
		return locPostal;
	}

	public void setLocPostal(String locPostal) {
		this.locPostal = locPostal;
		this.pk.setLocPostal(locPostal);
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getPrefijo() {
		return prefijo;
	}

	public void setPrefijo(Integer prefijo) {
		this.prefijo = prefijo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((pk == null) ? 0 : pk.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		LocalidadEntity other = (LocalidadEntity) obj;
		if (pk == null) {
			if (other.pk != null)
				return false;
		} else if (!pk.equals(other.pk))
			return false;
		return true;
	}
}
