package com.cairone.sdlpocjpa.entities;
// Generated 08/06/2016 10:42:19 by Hibernate Tools 3.4.0.CR1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.cairone.sdlpocjpa.enums.MonedaCotizacionClaseEnum;

/**
 * MonedaCot generated by hbm2java
 */
@Entity @Table(name="MONEDA_COT")
public class MonedaCotizacionEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	@EmbeddedId private MonedaCotizacionPKEntity pk = null;

	@Column(name="fecha", nullable=false, insertable=false, updatable=false, length=23) @Temporal(TemporalType.TIMESTAMP)
	private Date fecha = null;
	
	@Column(name="tipo_cotizacion", nullable=false, insertable=false, updatable=false)
	private MonedaCotizacionClaseEnum clase = null;

	@ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="moneda_tipo", nullable=false, insertable=false, updatable=false)
    private MonedaEntity moneda = null;

	@Column(name="valor", precision=8, scale=4)
    private BigDecimal valor = null;

	@Column(name="cantidad")
    private Integer cantidad = null;

    public MonedaCotizacionEntity() {
    	this.pk = new MonedaCotizacionPKEntity();
    }

	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
		this.pk.setFecha(fecha);
	}

	public MonedaCotizacionClaseEnum getClase() {
		return clase;
	}

	public void setClase(MonedaCotizacionClaseEnum clase) {
		this.clase = clase;
		this.pk.setMonedaCotizacionClaseEnum(clase);
	}

	public MonedaEntity getMoneda() {
		return moneda;
	}

	public void setMoneda(MonedaEntity moneda) {
		this.moneda = moneda;
		this.pk.setMonedaTipo(moneda.getId());
	}

	public BigDecimal getValor() {
		return valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public Integer getCantidad() {
		return cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((pk == null) ? 0 : pk.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MonedaCotizacionEntity other = (MonedaCotizacionEntity) obj;
		if (pk == null) {
			if (other.pk != null)
				return false;
		} else if (!pk.equals(other.pk))
			return false;
		return true;
	}   
}
